# Generated by Django 2.1.15 on 2026-05-16 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('full_address', models.TextField(blank=True)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('street_address', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_amount', models.IntegerField()),
                ('status', models.CharField(choices=[('new', 'Новый'), ('collecting', 'Собирается'), ('in_transit', 'В пути'), ('delivered', 'Доставлено'), ('cancelled', 'Отменён')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(default='Animal-hoods.ru', max_length=100)),
                ('courier_name', models.CharField(blank=True, max_length=100)),
                ('delivery_date', models.DateField(blank=True, null=True)),
                ('time_restrictions', models.CharField(blank=True, max_length=200)),
                ('send_cdek', models.BooleanField(default=False)),
                ('cdek_tariff', models.CharField(blank=True, choices=[('parcel_warehouse', 'Посылка склад-склад'), ('parcel_door', 'Посылка склад-дверь'), ('economy', 'Экономичная посылка'), ('express', 'Экспресс'), ('standard_door', 'Стандартная доставка до двери')], max_length=50)),
                ('cdek_length', models.IntegerField(blank=True, null=True)),
                ('cdek_width', models.IntegerField(blank=True, null=True)),
                ('cdek_height', models.IntegerField(blank=True, null=True)),
                ('cdek_weight', models.IntegerField(blank=True, null=True)),
                ('cdek_city', models.CharField(blank=True, max_length=100)),
                ('cdek_pickup_address', models.TextField(blank=True)),
                ('cdek_street', models.CharField(blank=True, max_length=200)),
                ('cdek_house', models.CharField(blank=True, max_length=20)),
                ('cdek_apartment', models.CharField(blank=True, max_length=20)),
                ('delivery_cost_customer', models.IntegerField(default=0)),
                ('delivery_cost_actual', models.IntegerField(default=0)),
                ('discount', models.IntegerField(default=0)),
                ('promo_discount', models.IntegerField(default=0)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='dashboard.Customer')),
            ],
            options={
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('custom_price', models.IntegerField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.Order')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('size', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Product categories',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='dashboard.ProductCategory'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Product'),
        ),
    ]
